version: '3'

services:
  bot:
    build: .
    env_file:
      - ./secrets.env
    init: true
  deploy:
    build: .
    env_file:
      - ./secrets.env
    init: true
    command: node deploy.js
